# Generated by Django 5.1.6 on 2025-02-27 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipeingredient',
            name='quantity',
            field=models.CharField(default='1pc', max_length=100),
        ),
    ]
